// auto-generated by napi-rs
// @ts-check
'use strict';

let nativeRequire;
try {
  nativeRequire = require('node-pre-gyp');
} catch (e) {
  // fall through
}

if (!nativeRequire) {
  try {
    nativeRequire = require('@mapbox/node-pre-gyp');
  } catch (e) {
    // fall through
  }
}

const path = require('path');
const mod = nativeRequire
  ? nativeRequire.find(path.resolve(__dirname, 'package.json'))
  : undefined;

const binding = mod
  ? mod.require(path.resolve(__dirname))
  : require(path.resolve(__dirname, 'pos_printer_driver.node'));

module.exports = binding;
